[package]
name = "token-manager-mint-burn-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.token-manager-mint-burn]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.4"
