name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v2.3.1
    with:
      rust-toolchain: nightly-2023-05-26
      vmtools-version: v1.4.60
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: xSuite Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-05-26
          target: wasm32-unknown-unknown

      - name: Setup the PATH variable
        run: |
          echo "PATH=$HOME/.local/bin:$HOME/multiversx-sdk/vmtools:$PATH" >> $GITHUB_ENV

      - name: Install prerequisites
        run: |
          pip3 install multiversx-sdk-cli==v8.1.2
          mkdir $HOME/multiversx-sdk
          python3 -m multiversx_sdk_cli.cli deps install vmtools --tag v1.4.60
          
          wget -O binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_112/binaryen-version_112-x86_64-linux.tar.gz
          tar -xf binaryen.tar.gz
          cp binaryen-version_112/bin/wasm-opt $HOME/.local/bin

          sudo apt install -y wabt=1.0.27-1

          cargo install twiggy
          
          cargo install multiversx-sc-meta
          
          which wasm-opt
          which wasm2wat
          which run-scenarios

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build:ci
      - run: npm run test
